### ISSUE TITLE
purgeCSS not working in development

### ISSUE THREAD

**Issue by AeonFr** [nuxt-community/nuxt-tailwindcss#47]
The installation of purgeCSS works fine, but it doesn't purge in development.
However, when running `nuxt generate`, purgeCSS does run.

This creates a very unpleasant experience, because some classes are added dinamicaly, and there's no way to detect if they will be purged or not until after development.

It would be nice to:

- Have option to disable purgeCSS
- Apply purgeCSS during development

Reproduce:

Run `create-nuxt-app` with "tailwind" module, then create a component that applies a class dinamicaly, like:

```
<div :class="`m-${size}`"/>
```

Then run `nuxt generate`, the class won't be applied.

**Comment by manniL** [comment]
Hey 👋 

Yes, that's a common problem which should be caught at least in the staging environment (due to the "production-like" setting there). 

Running purgeCSS in development is possible, though it'll increase HMR time and need a custom setup (so you have to use https://github.com/Developmint/nuxt-purgecss + your own code to set up tailwind).

Currently, the module isn't adding purgeCSS in dev mode:

https://github.com/nuxt-community/nuxt-tailwindcss/blob/master/lib/module.js#L48-L53


Completely disabling it is possible through the `enabled` function https://github.com/Developmint/nuxt-purgecss#defaults

**Comment by AndrewBogdanovTSS** [comment]
@manniL But it should work with regular build command, right?

**Comment by manniL** [comment]
Yes! ☺️

**Comment by AndrewBogdanovTSS** [comment]
Yeah, as you know @manniL it was sorted out 😁
